apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fossflow-ingress
  namespace: fossflow
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: fossflow.k3s.alexmihai.rocks
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fossflow
                port:
                  number: 80
  tls:
    - hosts:
      - fossflow.k3s.alexmihai.rocks
      secretName: fossflow-k3s-tls
