services:
  metube:
    image: ghcr.io/alexta69/metube:2026.02.01
    container_name: metube
    security_opt:
      - apparmor=unconfined
    restart: unless-stopped
    ports:
      - 8082:8081
    volumes:
      - /srv/dev-disk-by-uuid-55a53b5a-a4c9-4b6b-83af-9358690d4380/ssd1/metube:/downloads