apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bentopdf-ingress
  namespace: bento
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: bento.alexmihai.rocks
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bentopdf-service
                port:
                  number: 8080
  # tls: resolved externally by Nginx Proxy Manager
  